// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbWebScraper.Models;

public partial class fileTypeAllowedToScrapeTbl
{
    public string fileExt { get; set; }
}