// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbWebScraper.Models;

public partial class hostPageLinkErrorsQry
{
    public int id { get; set; }

    public int hostId { get; set; }

    public string host { get; set; }

    public string pageUri { get; set; }

    public string rawLink { get; set; }

    public string linkUri { get; set; }

    public string innerHtml { get; set; }

    public string outerHtml { get; set; }

    public int scrapeId { get; set; }

    public string scrapeUri { get; set; }

    public string statusCode { get; set; }

    public string errorText { get; set; }

    public DateTime? scrapeDateTime { get; set; }
}