// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DbWebScraper.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DbWebScraper.Models
{
    public partial interface IWebScraperContextProcedures
    {
        Task<int> deleteHostScrapeByIdSpAsync(int? hostId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> deleteHostScrapeByNameSpAsync(string host, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> fixAbsoluteUriAsync(string oldUri, string newUri, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> pageDeleteWhereHostIsSkippedAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> scrapeTblDeleteRowsNotInPageAndLinksSpAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
