// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbWebScraper.Models;

public partial class scapeLinksThatShouldBeInPages
{
    public int hostId { get; set; }

    public int scrapeId { get; set; }

    public string absoluteUri { get; set; }
}