// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScraperCode.DbCtx;

public partial class hostWithoutAnyPages
{
    public int id { get; set; }

    public int maxPageToScrape { get; set; }

    public string host { get; set; }

    public string path { get; set; }

    public string runNotes { get; set; }

    public DateTime addedDateTime { get; set; }

    public bool reportDone { get; set; }
}