// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScraperCode.DbCtx;

public partial class linkTbl
{
    public int id { get; set; }

    public int pageId { get; set; }

    public int? indexOnPage { get; set; }

    public int scrapeId { get; set; }

    public string rawLink { get; set; }

    public string absoluteUri { get; set; }

    public string innerHtml { get; set; }

    public string outerHtml { get; set; }

    public DateTime addedDateTime { get; set; }

    public virtual pageTbl page { get; set; }

    public virtual scrapeTbl scrape { get; set; }
}