// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScraperCode.DbCtx;

public partial class logTbl
{
    public int id { get; set; }

    public string text { get; set; }

    public DateTime addedDateTime { get; set; }
}