// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScraperCode.DbCtx;

public partial class pageScrapeQry
{
    public int hostId { get; set; }

    public int pageId { get; set; }

    public string host { get; set; }

    public string pageAbsoluteUri { get; set; }

    public string scrapeUri { get; set; }

    public int pageNotInScrapeTable { get; set; }

    public string fileExt { get; set; }

    public string statusCode { get; set; }

    public string html { get; set; }

    public DateTime? scrapeDateTime { get; set; }
}