// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScraperCode.DbCtx;

public partial class pageTbl
{
    public int id { get; set; }

    public int hostId { get; set; }

    public int scrapeId { get; set; }

    public string scheme { get; set; }

    public string host { get; set; }

    public string path { get; set; }

    public string fileExt { get; set; }

    public bool fileExtFixed { get; set; }

    public string query { get; set; }

    public int port { get; set; }

    public string absoluteUri { get; set; }

    public DateTime addedDateTime { get; set; }

    public int linkCount { get; set; }

    public virtual ICollection<linkTbl> linkTbl { get; set; } = new List<linkTbl>();
}