// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScraperCode.DbCtx;

public partial class scrapeTbl
{
    public int id { get; set; }

    public string host { get; set; }

    public string absoluteUri { get; set; }

    public DateTime addedDateTime { get; set; }

    public string statusCode { get; set; }

    public string errorText { get; set; }

    public DateTime? scrapeDateTime { get; set; }

    public string html { get; set; }

    public string headStatusCode { get; set; }

    public string headContentType { get; set; }

    public string headContentHeaders { get; set; }

    public string headResponseHeaders { get; set; }

    public string headErrorMessage { get; set; }

    public string fileExt { get; set; }

    public virtual ICollection<linkTbl> linkTbl { get; set; } = new List<linkTbl>();
}