// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScraperCode.DbCtx;

public partial class scrapeQueueQry
{
    public int scrapeId { get; set; }

    public bool? addPages { get; set; }

    public int? pageId { get; set; }

    public int? hostPageCount { get; set; }

    public int? hostMaxPagesToScrape { get; set; }

    public string fileExt { get; set; }

    public string host { get; set; }

    public string absoluteUri { get; set; }

    public string headStatusCode { get; set; }

    public string statusCode { get; set; }
}