// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbScraper02.Models;

public partial class hostPageLinkErrorsQry
{
    public int id { get; set; }

    public string host { get; set; }

    public string pageCleanLink { get; set; }

    public int statusCode { get; set; }

    public string rawLink { get; set; }

    public string linkCleanLink { get; set; }

    public string innerHtml { get; set; }

    public string outerHtml { get; set; }

    public int scrapeId { get; set; }

    public string scrapeCleanLink { get; set; }

    public DateTime addedDateTime { get; set; }
}