// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbScraper02.Models;

public partial class hostQry
{
    public int id { get; set; }

    public string host { get; set; }

    public int? hostLinkCount { get; set; }

    public int maxPageToScrape { get; set; }

    public DateTime addedDateTime { get; set; }
}