// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbScraper02.Models;

public partial class hostTbl
{
    public int id { get; set; }

    public int maxPageToScrape { get; set; }

    public string host { get; set; }

    public DateTime addedDateTime { get; set; }

    public bool reportDone { get; set; }

    public string category { get; set; }

    public int redirectStatusCode { get; set; }

    public string redirectedToHost { get; set; }

    public DateTime? redirectLastVerified { get; set; }
}