// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbScraper02.Models;

public partial class linkTbl
{
    public int id { get; set; }

    public int uniqueId { get; set; }

    public int indexOnPage { get; set; }

    public string absoluteUri { get; set; }

    public string rawLink { get; set; }

    public string innerHtml { get; set; }

    public string outerHtml { get; set; }

    public DateTime addedDateTime { get; set; }

    public string errorMessage { get; set; }

    public virtual linkUniqueTbl unique { get; set; }
}