// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbScraper02.Models;

public partial class pageTbl
{
    public int id { get; set; }

    public string host { get; set; }

    public string cleanLink { get; set; }

    public string fullLink { get; set; }

    public DateTime addedDateTime { get; set; }

    public int linkCount { get; set; }

    public int linkCountOverLimit { get; set; }
}