// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DbScraper02.Models;

public partial class Scraper02Context : DbContext
{
    public Scraper02Context(DbContextOptions<Scraper02Context> options)
        : base(options)
    {
    }

    public virtual DbSet<hostTbl> hostTbl { get; set; }

    public virtual DbSet<logTbl> logTbl { get; set; }

    public virtual DbSet<tmpHostTransferQry> tmpHostTransferQry { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<hostTbl>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK_hostPathToScrapeTbl");

            entity.Property(e => e.addedDateTime).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.category)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.errorMessage)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.host)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.maxPageToScrape).HasDefaultValue(-1);
            entity.Property(e => e.redirectedToHost)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<logTbl>(entity =>
        {
            entity.Property(e => e.addedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.text)
                .IsRequired()
                .IsUnicode(false);
        });

        modelBuilder.Entity<tmpHostTransferQry>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("tmpHostTransferQry");

            entity.Property(e => e.category)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.host)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.id).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}