// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DbScraper02.Models;

public partial class Scraper02Context : DbContext
{
    public Scraper02Context(DbContextOptions<Scraper02Context> options)
        : base(options)
    {
    }

    public virtual DbSet<logTbl> logTbl { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<logTbl>(entity =>
        {
            entity.Property(e => e.addedDateTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.text)
                .IsRequired()
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}