// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DbScraper02.Models;

public partial class scrapeTbl
{
    public int id { get; set; }

    public string host { get; set; }

    public string cleanLink { get; set; }

    public int statusCode { get; set; }

    public string html { get; set; }

    public string contentType { get; set; }

    public string contentHeaders { get; set; }

    public string responseHeaders { get; set; }

    public string errorMessage { get; set; }

    public DateTime addedDateTime { get; set; }

    public DateTime? scrapeDateTime { get; set; }
}