// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DbScraper02.Models
{
    public partial class scrapeQueueSpResult
    {
        public int scrapeId { get; set; }
        [StringLength(100)]
        public string host { get; set; }
        public bool shouldAddPage { get; set; }
        [StringLength(2147483647)]
        public string cleanLink { get; set; }
        public int statusCode { get; set; }
        public int maxPageToScrape { get; set; }
        public int? queueCount { get; set; }
    }
}
